export const DropdownOptions = [
  {
    id: "1",
    value: "null",
    title: "Select Emotion",
  },
  { id: "2", value: "Afraid", title: "Afraid" },
  { id: "3", value: "Angry", title: "Angry" },
  { id: "4", value: "Anxious", title: "Anxious" },
  { id: "5", value: "Treated-harshly", title: "Been treated harshly" },
  { id: "6", value: "Depressed", title: "Depressed" },
  { id: "7", value: "Desire", title: "Desire" },
  { id: "8", value: "Burdened", title: "Feeling burdened" },
  { id: "9", value: "Loser", title: "Feeling like a loser" },
  { id: "10", value: "Lonely", title: "Feeling lonely" },
  { id: "11", value: "Proud", title: "Feeling proud" },
  { id: "12", value: "Underpriviledged", title: "Feeling underpriviledged" },
  { id: "13", value: "Weak", title: "Feeling weak" },
  { id: "14", value: "Upset", title: "Feeling upset" },
  { id: "15", value: "Danger", title: "In danger" },
  { id: "16", value: "Lost-hope", title: "Lost Hope" },
  { id: "17", value: "Lack-of-faith", title: "Lack of faith" },
  { id: "18", value: "Courage", title: "Need courage" },
  { id: "19", value: "Not-appreciated", title: "Not Appreciated" },
  { id: "20", value: "Direction", title: "Need direction" },
  {
    id: "21",
    value: "Overwhelmed-with-hardships",
    title: "Overwhelmed with harships",
  },
  {
    id: "22",
    value: "Love-and-tranquility",
    title: "Seeking love n tranquility",
  },
  { id: "23", value: "Seeking-peace", title: "Seaking peace" },
  { id: "24", value: "Seeking-patience", title: "Seaking patience" },
  { id: "25", value: "Stay-steadfast", title: "Struggling to stay steadfast" },
  { id: "26", value: "Hard-on-myself", title: "Too hard on myself" },
  { id: "27", value: "Unhappy", title: "Unhappy" },
  { id: "28", value: "Wishing-friend", title: "Wishing for a friend" },
];
